// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    /* Generated by `expo start`, gitignored, and it carries its own
       eslint-disable that this config has nothing to say about. */
    ignores: ['dist/*', '.expo/*', '.tmp-*/*'],
  },
  {
    /* Build scripts are CommonJS and run by node directly, so `__dirname` and
       friends are real. The default config assumes ESM app source. */
    files: ['scripts/**/*.js', 'eslint.config.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { __dirname: 'readonly', __filename: 'readonly', require: 'readonly', module: 'writable', process: 'readonly' },
    },
  },
]);
