/**
 * The four starter capsules.
 *
 * TWO PROPERTIES MUST HOLD, and they are what make the capsules free:
 *   1. every capsule covers all five slots — so no choice can lock a new player
 *      out of entering
 *   2. the capsules overlap — so all four draw from one shared pool and add no
 *      new assets
 *
 * If someone edits the piece lists, these tests are what catch a capsule that
 * has, say, no shoes.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { SLOTS, slotOf } from '../src/domain/garments.ts';
import { CAPSULES, coversAllSlots, slotsCovered } from '../src/data/capsules.ts';
import { inventoryDayOne, inventoryDayTwo } from '../src/data/inventory.ts';
import { CUTOUT_ASPECT } from '../src/data/cutoutAspects.ts';
import { STARTER_CAPSULE_SIZE } from '../src/domain/economy.ts';

test('there are four capsules', () => {
  assert.equal(CAPSULES.length, 4);
});

test('EVERY capsule covers all five slots — no capsule can lock you out', () => {
  for (const c of CAPSULES) {
    assert.ok(
      coversAllSlots(c),
      `${c.name} misses ${SLOTS.filter((s) => !slotsCovered(c).includes(s)).join(', ')}`,
    );
  }
});

test('every capsule is the starter size', () => {
  for (const c of CAPSULES) {
    assert.equal(c.pieces.length, STARTER_CAPSULE_SIZE, `${c.name} is the wrong size`);
  }
});

test('the capsules deliberately overlap, so they cost no new assets', () => {
  const counts = new Map<string, number>();
  for (const c of CAPSULES) for (const p of c.pieces) counts.set(p, (counts.get(p) ?? 0) + 1);

  const shared = [...counts.entries()].filter(([, n]) => n > 1).map(([p]) => p);
  assert.ok(shared.length >= 3, `expected overlap, found ${shared.length} shared pieces`);
  // The three the handover names explicitly.
  for (const p of ['roll neck', 'wide leg', 'silk shirt']) {
    assert.ok(shared.includes(p), `${p} should appear in more than one capsule`);
  }

  const distinct = counts.size;
  const naive = CAPSULES.length * STARTER_CAPSULE_SIZE;
  assert.ok(distinct < naive, 'overlap should mean fewer distinct pieces than 4 × 8');
});

test('day one inventory is exactly the capsule you chose, nothing worn', () => {
  for (const c of CAPSULES) {
    const inv = inventoryDayOne(c.key);
    assert.equal(inv.length, c.pieces.length);
    assert.ok(inv.every((p) => p.worn === 0 && p.best === null));
    assert.ok(inv.every((p) => p.provenance === 'starter'));
  }
});

/* ══════════════════════════════════════════════════════════════════════════
   THE RETURNING STATE'S WARDROBE (ACTIVE_DAY 2)
   ══════════════════════════════════════════════════════════════════════════

   ⟲ REWRITTEN 13 Sep. This used to assert the capsule-derived shape —
   `STARTER_CAPSULE_SIZE + 3` pieces, three 'taken' arrivals, one worn piece per
   slot. All three were properties of a fixture that was DERIVED FROM THE
   CAPSULES, and that derivation was the bug: the capsule names are original
   prototype short names and the AW26 catalogue carries none of them, so day 2
   drew a grey named box in place of every garment. The old assertions passed
   throughout, because none of them looked at whether a name was real.

   That is what the first test below now checks, and it is the one worth having.
   The "no capsule can lock you out" invariant is still covered — by the capsule
   tests above, which is where it belongs. */

test('EVERY day-two piece is a real catalogue name — the cutout must load', () => {
  /* `CUTOUT_ASPECT` is generated by reading `assets/garments/*.png`, so its
     keys are exactly the cutouts that EXIST on disk. Asserting against it
     proves the photograph will load, which is stronger than asserting against
     the catalogue's own list — and it is importable here, whereas
     data/catalogue.ts require()s sixty PNGs the plain-Node runner cannot load.
     Lowercased on both sides because the keys come from kebab filenames and
     cannot carry the catalogue's one capitalised name. */
  const known = new Set(Object.keys(CUTOUT_ASPECT).map((k) => k.toLowerCase()));
  for (const p of inventoryDayTwo()) {
    assert.ok(known.has(p.name.toLowerCase()), `no cutout for "${p.name}"`);
  }
});

test('day two covers all five slots, several pieces deep', () => {
  const inv = inventoryDayTwo();
  assert.equal(inv.length, 30);

  /* A slot the picker opens onto one option is a drawer that wastes a tap, and
     a slot with none is a look that cannot be built. */
  for (const slot of SLOTS) {
    const n = inv.filter((p) => slotOf(p.name) === slot).length;
    assert.ok(n >= 3, `only ${n} pieces in ${slot}`);
  }
});

test('day two reads as accumulated, not granted', () => {
  const inv = inventoryDayTwo();

  /* No duplicates: the store keys pieces by name, so a repeat is a row that
     cannot be removed. */
  assert.equal(new Set(inv.map((p) => p.name)).size, inv.length);

  /* Most of it was TAKEN — invariant 1, every one of those cost a judging
     round. A wardrobe of thirty 'starter' pieces would say clothes are free. */
  assert.ok(inv.filter((p) => p.provenance === 'taken').length >= inv.length / 2);

  /* Arrivals are flagged, but only a couple of them — `isNew` is the Klein
     outline, and a grid where everything is new reads as bought all at once. */
  const fresh = inv.filter((p) => p.isNew);
  assert.ok(fresh.length > 0 && fresh.length <= 4, `${fresh.length} new pieces`);

  /* `worn`/`best` are the only per-piece history in the app (invariant 14 keeps
     them out of the builder), so they have to be non-trivial — and an unworn
     piece must never carry a band. */
  assert.ok(inv.some((p) => p.worn > 0) && inv.some((p) => p.worn === 0));
  assert.ok(inv.every((p) => (p.worn === 0 ? p.best === null : true)));
});
